In [1]:
from sudoku_numpy import Board, Game, Solver
import numpy as np
import matplotlib.pyplot as plt
import time

In [2]:
g = Game(num_players=2)
g.generate_views()
s = Solver(g)

solvable_boards = s.generate_greedy()

search time limit exceeded
backtrack time: 42.94 s
search time: 30.08 s


In [5]:
b = solvable_boards[-1]
print(b)

g.board = b
s = Solver(g)
s.iterative_solve()
print(s.solution)


[[14  0 13  0  2  7  0  0  0  1 15  6 10 12  0  0]
 [ 0  0  0  9 10  0 13  4  0 14  0  7  0  0  0 15]
 [ 0  5  0 15  6  0 12  0 10 13  4  0  9 14  0  7]
 [ 0  0 10  0  0 14  0  0 16  0  9  2  4  0  0  0]
 [ 0  0  0  0  0  0  2 10 14 16  8  5  0  4 12  0]
 [ 0  3  0  0  0 11  0  1  0 10  6  0  0  0  0  0]
 [16 14  0 12  8  5  3  0  0 11  2  4  0 15  0  0]
 [10  0  0  0  0  0  0  0 15  0  0  0  7 11  5  0]
 [ 0  0  0  0 14  2  8 16  0  5  3 10  0 13  0  0]
 [ 0  0  0 11  0  0  7  6  0  4 13  1 14  0  0 10]
 [ 0  8  0 16  3  9  0  0  2  0 12  0  1  0  7  4]
 [15  0  0  0  4  1  0 13  9  7  0  0  0  2  3  0]
 [ 0  0  1  0  9  0  0  0  0  0  0 11  5  0  4  8]
 [ 8 15  0  3  0  0  0  2  0  9  5  0 11  0  0  0]
 [ 4 16  0  0 11 10  0  0  0  0  7 12  3  0  0 13]
 [ 0 10  0  0  5  4  0 12  1  8 16  3 15  0  2  9]]
[(0, 2), (0, 4), (0, 9), (0, 10), (0, 11), (1, 3), (1, 4), (1, 6), (1, 15), (2, 1), (2, 4), (2, 9), (2, 10), (3, 2), (3, 5), (3, 11), (3, 12), (4, 6), (4, 7), (4, 10), (4, 13), (4, 14