In [1]:
from sudoku_numpy import Board, Game, Solver
import numpy as np
import matplotlib.pyplot as plt
import time

In [2]:
g = Game(num_players=2)
g.generate_views()
s = Solver(g)

solvable_boards = s.generate_greedy()

In [6]:
print(solvable_boards[-1])

[[ 4  1  0 15  6 16  0  8  7  0  0  0  0 14  0 10]
 [14  0  7  0  0  2  0  0  0  0  0  3  0  0  9  0]
 [ 0  6  8  0  0  0  7  4 15  0 12 10  5  0  1  0]
 [10 16  0  3 12  5  0  9  4  0  0 11  6  7 13  0]
 [ 5  0  0 12 13  0  0 10  0  0  0 16  0  0  7  8]
 [ 0 13  0  0  1  0  0  0  0  0  8  6 15  3 10  0]
 [ 0  0  0  4 16  0  0  7  3  0  2 12  0  0  0 14]
 [ 9  0 11  0  0 12 14  0  0  7  5 15  0  4 16  0]
 [ 0  0  9  2  0  0  0 16  0  0  0  0  0 12  3  0]
 [ 3  0 12  1 11  4  0  2  0  0  0 14  7  0  0  0]
 [ 0  8 14 16  0  0  5  0 12  6  0  0  1 11  0  0]
 [13  0 10 11  0  0 15  0  8  5  3  2 14  0  0  6]
 [ 0  0  0 10  4  6  0 14  2  0  0  0 13  5 12  0]
 [ 0  0  0 13  2  0  0  0  0 14 11  0  0 10  0  7]
 [ 0 14  0  0  0  7 11  0  1  0 16  0  0  9  0  4]
 [12 11  4  0  0  9  0 15  0  0  0 13  8  0  0  2]]


In [6]:
print(s.board)

[[16  3  8 10  2 12  1 11  7 13  5  6 15 14  4  9]
 [ 4  7 11  6  9  3 14 10 12 16  1 15  5 13  8  2]
 [12 14  5  2 16 15  7 13  3  9  4  8  6  1 10 11]
 [13  9 15  1  6  5  8  4 14 10 11  2  7 16 12  3]
 [ 9  5 16  3  4 11 12  6 13 14  7 10  2 15  1  8]
 [ 7 13 12  8 14  2  9 15 16  6  3  1 10  4 11  5]
 [10  1 14 11 13  8  5 16  2 12 15  4  9  6  3  7]
 [15  6  2  4  1  7 10  3  9 11  8  5 13 12 14 16]
 [ 3 10  1  9  8  4 13  5 15  7 16 12 14 11  2  6]
 [11  8  7  5 10  9 15  1  6  4  2 14 16  3 13 12]
 [ 6 16  4 15 12 14  3  2  8  5 13 11  1  7  9 10]
 [ 2 12 13 14 11 16  6  7 10  1  9  3  8  5 15  4]
 [ 1  4  9  7 15 10 11 14  5  2 12 16  3  8  6 13]
 [ 8  2  6 12  7  1 16  9  4  3 14 13 11 10  5 15]
 [ 5 11 10 16  3 13  4  8  1 15  6  9 12  2  7 14]
 [14 15  3 13  5  6  2 12 11  8 10  7  4  9 16  1]]


In [14]:
b = solvable_boards[-1]
g.board = b
s = Solver(g)
print(b)
s.iterative_solve()
print(s.board)
print(g.views)


[[0 9 6 0 0 2 0 8 0]
 [0 7 3 0 9 6 0 0 0]
 [0 0 0 7 0 3 0 0 9]
 [0 1 0 0 6 0 0 9 0]
 [4 0 0 2 7 0 5 0 0]
 [0 0 0 0 0 8 0 0 4]
 [0 4 0 1 0 0 7 6 0]
 [0 0 2 0 0 9 0 5 0]
 [0 0 1 3 4 0 9 2 8]]
[[5 9 6 4 1 2 3 8 7]
 [1 7 3 8 9 6 2 4 5]
 [8 2 4 7 5 3 6 1 9]
 [3 1 7 5 6 4 8 9 2]
 [4 8 9 2 7 1 5 3 6]
 [2 6 5 9 3 8 1 7 4]
 [9 4 8 1 2 5 7 6 3]
 [7 3 2 6 8 9 4 5 1]
 [6 5 1 3 4 7 9 2 8]]
[[[0. 0. 1. 1. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 1. 1. 0. 1. 0. 1. 1. 0.]
  [1. 1. 0. 0. 0. 1. 1. 1. 0.]
  [1. 0. 0. 0. 0. 0. 1. 1. 1.]
  [0. 0. 0. 0. 0. 1. 1. 0. 1.]
  [0. 1. 0. 0. 1. 1. 1. 1. 0.]
  [1. 0. 0. 0. 0. 1. 0. 0. 0.]
  [1. 0. 1. 0. 0. 0. 1. 0. 0.]]

 [[1. 1. 0. 1. 0. 1. 1. 1. 1.]
  [0. 0. 1. 0. 1. 0. 1. 0. 0.]
  [0. 0. 1. 0. 0. 0. 1. 0. 0.]
  [0. 0. 1. 1. 0. 1. 0. 0. 0.]
  [0. 1. 1. 1. 1. 1. 0. 1. 1.]
  [1. 0. 0. 1. 1. 1. 0. 1. 0.]
  [1. 1. 1. 1. 0. 0. 0. 0. 1.]
  [1. 0. 0. 1. 1. 0. 1. 1. 1.]
  [0. 0. 1. 1. 1. 0. 0. 0. 0.]]

 [[1. 0. 0. 0. 1. 0. 1. 1. 0.]
  [1. 1. 0. 1. 0. 1. 1. 1. 